#!/bin/bash
printf "\n\t Testing Existence of System Files \n\n"
[ -f /usr/bin/which ] && echo "True: /usr/bin/Which" || echo "False: Missing /usr/bin/which"
[ ! -f /etc/dircolors ] && dircolors -p > /etc/dircolors || echo "True: /etc/dircolors"
[ -f /etc/bashrc ] && echo "True: /etc/bashrc" || echo "False: Missing: /etc/bashrc"
[ -f /etc/dircolors ] && echo "True: /etc/dircolors" || echo "False: Missing: /etc/dircolors"
[ -f /etc/fstab ] && echo "True: /etc/fstab" || echo "False: Missing: /etc/fstab"
[ -f /etc/hosts ] && echo "True: /etc/hosts" || echo "False: Missing: /etc/hosts"
[ -f /etc/inputrc ] && echo "True: /etc/inputrc" || echo "False: Missing: /etc/inputrc"
[ -f /etc/profile ] && echo "True: /etc/profile" || echo "False: Missing: /etc/profile"
[ -f /etc/resolv.conf ] && echo "True: /etc/resolv.conf" || echo "False: Missing: /etc/resolv.conf"
[ -f /etc/vimrc ] && echo "True: /etc/vimrc" || echo "False: Missing: /etc/vimrc"
[ -f /etc/nanorc ] && echo "True: /etc/nanorc" || echo "False: Missing: /etc/nanorc"
[ -f /root/.bash_profile ] && echo "True: /root/.bash_profile" || echo "False: Missing: /root/.bash_profile"
[ -f /root/.bashrc ] && echo "True: /root/.bashrc" || echo "False: Missing: /root/.bashrc"

printf "\t If good next Firmware Install using Git \n"
printf "\t or Logout with unmount rootvfs and lfs-rootvfs \n"
printf "\t Done \n"
