#!/bin/bash
#
#   Blank Install zbuild
#   unset functions
unset -f Src_package
unset -f Src_prepare
unset -f Src_configure
unset -f Src_compile
unset -f Src_check
unset -f Src_install
unset -f Src_post
#
#  Global
#
BUILD_SOURCE=/opt/source
BUILD_ROOT=/BUILD
BUILD_LOG=$BUILD_ROOT/Zbuild_Logs

package=
archive=$(find $BUILD_SOURCE -name "${package}*.tar.*" | head -n 1 | xargs basename)
delete="true"
extract="true"
patch="false"

#
#   Build Functions
# 
Src_Extract() {
    echo "*** Extracting: ${package} ***"

}
# First Remove the .tar.* and Second Get Package Name
Src_package() {
    packagedir=${archive%.tar.*}
    package=${packagedir%-*}
}
# Executed After pushd
Src_prepare () {
   echo "*** Preparing ${package} ***"

}
Src_configure () {
   echo "*** Configuring ${package} ***"
   ./configure ${prefix} ${disable} ${docdir} || exit 88
}
Src_compile () {
   echo "*** Compiling ${package} ***"
   make 2>&1 | tee $BUILD_LOG/${package}-make.log || exit 77
}
Src_check () {
   echo "*** Checking ${package} ***"
   make check 2>&1 | tee $BUILD_LOG/${package}-check.log
}
Src_install () {
   echo "*** Installing ${package} ***"
   make install || exit 55
}
# Executed After popd
Src_post () {
   echo "*** Finalizing ${package} ***"

}
#
# Start defining package specific options
# 
prefix="--prefix=/usr"
disable="--disable-static"
docdir="--docdir=/usr/share/doc/${packagedir}"
enable="--enable-shared"

# Extract the base package name and version
Src_package
#Src_Extract

export package packagedir archive extract delete patch
export prefix disable docdir enable
export BUILD_SOURCE BUILD_ROOT BUILD_LOGS
export -f Src_prepare
export -f Src_configure
export -f Src_compile
export -f Src_check
export -f Src_install
export -f Src_post

$BUILD_ROOT/zbuild.sh
exit_code=$?

if [[ exit_code -ne 0 ]]; then
    echo "___ Error Code: $exit_code"
else
    echo "*** Success ***"
    unset -f Src_package
    unset -f Src_prepare
    unset -f Src_configure
    unset -f Src_compile
    unset -f Src_check
    unset -f Src_install
    unset -f Src_post
    unset package packagedir archive extract delete patch
    unset prefix disable docdir enable
fi
