#!/bin/bash
#   Blank Install zbuild
#   unset functions
#
unset -f Src_package
unset -f Src_prepare
unset -f Src_configure
unset -f Src_compile
unset -f Src_check
unset -f Src_install
unset -f Src_post
#
#   Global
#
BUILD_SOURCE=/opt/source
BUILD_ROOT=/BUILD
BUILD_LOGS=$BUILD_ROOT/zbuild_logs
package=
archive=$(find $BUILD_SOURCE -name "${package}*.tar.*" | head -n 1 | xargs basename)
extract="true"
delete="true"
patch="false"

#
#   Build Functions
# 
# First Remove the .tar.* and Second Get Package Name
Src_Extract() {
    echo "*** Extracting: ${package} ***"

}
Src_package() {
    packagedir=${archive%.tar.*}
    package=${packagedir%-*}

}
# executed after pushd
Src_prepare () {
   echo "*** Preparing ${package} ***"

}

Src_configure () {
   echo "*** Configuring ${package} ***"

}
Src_compile () {
   echo "*** Compiling ${package} ***"
   pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
}
Src_check () {
   echo "*** Checking ${package} ***"

}
Src_install () {
   echo "*** Installing ${package} ***"
   pip3 install --no-index --no-user --find-links dist {}
}
# executed after popd
Src_post () {
   echo "*** Finalizing ${package} ***"

}
#
# Start defining package specific options
# 

# Extract the base package name and version
Src_package
#Src_Extract

export package packagedir archive extract patch delete
export BUILD_SOURCE BUILD_ROOT BUILD_LOGS
export -f Src_prepare
export -f Src_configure
export -f Src_compile
export -f Src_check
export -f Src_install
export -f Src_post

$BUILD_ROOT/zbuild.sh
exit_code=$?

if [[ exit_code -ne 0 ]]; then
    echo "___ Error Code: $exit_code"
else
    echo "*** Success ***"
    unset -f Src_package
    unset -f Src_prepare
    unset -f Src_configure
    unset -f Src_compile
    unset -f Src_check
    unset -f Src_install
    unset -f Src_post
    unset package packagedir archive extract patch delete
fi

