#!/bin/bash
#   Blank Xorg Install zbuild
#   unset functions
#
unset -f Src_package
unset -f Src_prepare
unset -f Src_configure
unset -f Src_compile
unset -f Src_check
unset -f Src_install
unset -f Src_post
#
#   Global
#
BUILD_SOURCE=/opt/source
BUILD_ROOT=/BUILD
BUILD_LOGS=$BUILD_ROOT/Zbuild_Logs

package=
archive=$(find $BUILD_SOURCE -name "${package}*.tar.*" | head -n 1 | xargs basename)
delete="true"
extract="true"
patch="false"

#
#   Build Functions
# 
Src_Extract() {
    echo "*** Extracting: ${package} ***"

}
# First Remove the .tar.* and Second get Package Name
Src_package() {
    packagedir=${archive%.tar.*}
    package=${packagedir%-*}

}

Src_prepare () {
   echo "*** Preparing ${package} ***"

}

Src_configure () {
   echo "*** Configuring ${package} ***"
   ./configure ${prefix} ${sysconfdir} ${localstatedir} ${disable} || exit 88
}

Src_compile () {
   echo "*** Compiling ${package} ***"
   make || exit 77
}

Src_check () {
   echo "*** Checking ${package} ***"
   make check 2>&1 | tee $BUILD_LOGS/${package}-make-check.log
}

Src_install () {
   echo "*** Installing ${package} ***"
   make install || exit 55
}

Src_post () {
   echo "*** Finalizing ${package} ***"

}
#
# Start defining package specific options
# 
prefix="--prefix=/usr"
sysconfdir="--sysconfdir=/etc"
localstatedir="--localstatedir=/var"
disable="--disable-static"
docdir="--docdir=/usr/share/doc/${packagedir}"
# Extract the base package name and version
Src_package
#Src_Extract

export package packagedir archive extract delete patch
export prefix sysconfdir localstatedir disable docdir enable
export BUILD_SOURCE BUILD_ROOT BUILD_LOGS
export -f Src_prepare
export -f Src_configure
export -f Src_compile
export -f Src_check
export -f Src_install
export -f Src_post

$BUILD_ROOT/zbuild.sh
exit_code=$?

if [[ exit_code -ne 0 ]]; then
    echo "___ Error Code: $exit_code"
else
    echo "*** Success ***"
    unset -f Src_package
    unset -f Src_prepare
    unset -f Src_configure
    unset -f Src_compile
    unset -f Src_check
    unset -f Src_install
    unset -f Src_post
    unset package packagedir archive extract delete patch
    unset prefix sysconfdir localstatedir disable docdir enable
fi

